### ISSUE TITLE
Passing date value defaults to current date

### ISSUE THREAD

**Issue by arvi** [RobertLowe/autoform-pickadate#1]
Hi,

I am trying to pass a default date value on a pickadate input field so user can choose a date in calendar and when they got redirected to add/edit event, his/her selected date will be the default. However, it always defaults to current date, even if I pass the helper tag which results to date selected by user.

Here are my code snippets:

_client/templates/events.html_

``` javascript
{{eventStartDate}}
{{> afQuickField name='from_date' value=eventStartDate template="bootstrap3-horizontal" label-class="col-sm-3" input-col-class="col-sm-9"}}
```

---

_client/templates/events.js_

``` javascript
Template.Events.helpers({
    eventStartDate: function () {
        return Session.get('eventStartDate');
    }
});
```

---

_collections/libs/events.js_

``` javascript
Events = new Mongo.Collection("events");

Events.attachSchema(new SimpleSchema({
    from_date: {
      type: Date,
      label: 'From Date',
      autoform: {
        type: "pickadate",
        afFieldInput: {
          pickadateOptions: {
            format: 'dddd, d mmmm, yyyy',
            formatSubmit: 'yyyy-mm-dd'
          }
        }
      }
    }
});
```

---

Here is the output _(I displayed the eventStartDate before the autoform quick field to show that the helper function is working correctly when displayed as-is, but when passed in pickadate field, is overriden by current date)_:

![screen shot 2015-03-10 at 10 20 56 am - events](https://cloud.githubusercontent.com/assets/653750/6568290/0f204dac-c710-11e4-8b8a-dfcf246dab1a.png)

Thanks for your help! :)

**Comment by arvi** [comment]
Solved! It wasn't autoform, nor autoform-pickadate issue. It was my formatting problem. Found it by accident. :)

https://github.com/amsul/pickadate.js/issues/642#issuecomment-78392917

**Comment by RobertLowe** [comment]
Whoa, sorry I didn't even see this until now (I must of missed a notification), glad you figured it out!

Cheers!
