### ISSUE TITLE
Date translations (e.g. month names)?

### ISSUE THREAD

**Issue by brylie** [RobertLowe/autoform-pickadate#4]
We are developing an application primarily for non-english speakers. How can we translate the date strings, such as month names, into other languages?

**Comment by DanielDornhardt** [comment]
You can set the strings you like with pickadate: http://amsul.ca/pickadate.js/date/#translations

See the link in the docs to here: https://github.com/amsul/pickadate.js/tree/3.5.6/lib/translations - I basically copied the js for the language I needed and put it in Meteor.isClient(Meteor.startup(function()){ ... })

BÄM! Language support! :D

**Comment by brylie** [comment]
OK, thanks @DanielDornhardt :-)

**Comment by DanielDornhardt** [comment]
Hahaha @brylie , I know, Just in Time, right? :D You probably don't even remember the project by now :

**Comment by brylie** [comment]
Well, I had removed pickadate from our project, due to usability issue on iOS where the date field did not behave as expected on multi field forms. I.e. when a user was navigating the form fields, filling each in and clicking the iOS native 'next' button, the pickadate field would be skipped. This may have been something with my implementation, so we are trying it again.

**Comment by RobertLowe** [comment]
You should also be able to use `pickadateOptions` to apply settings instead of `Meteor.startup`

https://github.com/RobertLowe/autoform-pickadate/blob/master/autoform-pickadate.coffee#L54

---

@brylie Yea, that's more to do with `pickadate` itself, this library provides a very small implementation/wrapper around it. Sorry.

**Comment by brylie** [comment]
All good. I filed a support request with the upstream package, and we will look again to make sure I had done things correctly.
